IMPORTANT WARNING: Alignment column 975 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 976 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 979 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 980 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 981 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 982 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 983 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 984 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 985 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 986 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1047 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1132 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1186 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1484 contains only undetermined values which will be treated as missing data

IMPORTANT WARNING
Found 14 columns that contain only undetermined values which will be treated as missing data.
Normally these columns should be excluded from the analysis.

Just in case you might need it, an alignment file with 
undetermined columns removed is printed to file ./p.isolates.afa.reduced


Using BFGS method to optimize GTR rate parameters, to disable this specify "--no-bfgs" 



This is RAxML version 8.1.3 released by Alexandros Stamatakis on August 13 2014.

With greatly appreciated code contributions by:
Andre Aberer      (HITS)
Simon Berger      (HITS)
Alexey Kozlov     (HITS)
Kassian Kobert    (HITS)
David Dao         (KIT and HITS)
Nick Pattengale   (Sandia)
Wayne Pfeiffer    (SDSC)
Akifumi S. Tanabe (NRIFS)

Alignment has 611 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 51.72%

RAxML rapid bootstrapping and subsequent ML search

Using 1 distinct models/data partitions with joint branch length optimization



Executing 1000 rapid bootstrap inferences and thereafter a thorough ML search 

All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 611
Name: No Name Provided
DataType: DNA
Substitution Matrix: GTR




RAxML was called as follows:

raxmlHPC-PTHREADS -T 4 -f a -m GTRGAMMA -p 12345 -x 12345 -o Methanosarcina -# autoMRE -s ./p.isolates.afa -n LTDE.ML 



Time for BS model parameter optimization 0.230737
Bootstrap[0]: Time 1.722664 seconds, bootstrap likelihood -9631.553933, best rearrangement setting 13
Bootstrap[1]: Time 1.258262 seconds, bootstrap likelihood -9149.051440, best rearrangement setting 13
Bootstrap[2]: Time 1.524401 seconds, bootstrap likelihood -10591.183273, best rearrangement setting 12
Bootstrap[3]: Time 4.217797 seconds, bootstrap likelihood -9559.371135, best rearrangement setting 15
Bootstrap[4]: Time 1.491491 seconds, bootstrap likelihood -9630.045009, best rearrangement setting 10
Bootstrap[5]: Time 1.214196 seconds, bootstrap likelihood -9265.178807, best rearrangement setting 10
Bootstrap[6]: Time 1.239630 seconds, bootstrap likelihood -9762.327723, best rearrangement setting 6
Bootstrap[7]: Time 1.568445 seconds, bootstrap likelihood -9374.077019, best rearrangement setting 14
Bootstrap[8]: Time 1.514232 seconds, bootstrap likelihood -9942.871724, best rearrangement setting 5
Bootstrap[9]: Time 1.536255 seconds, bootstrap likelihood -9332.608511, best rearrangement setting 7
Bootstrap[10]: Time 1.552915 seconds, bootstrap likelihood -9977.527203, best rearrangement setting 7
Bootstrap[11]: Time 1.325001 seconds, bootstrap likelihood -9642.244419, best rearrangement setting 5
Bootstrap[12]: Time 1.402578 seconds, bootstrap likelihood -10208.388954, best rearrangement setting 8
Bootstrap[13]: Time 1.623110 seconds, bootstrap likelihood -10195.051146, best rearrangement setting 7
Bootstrap[14]: Time 1.354464 seconds, bootstrap likelihood -9599.565192, best rearrangement setting 12
Bootstrap[15]: Time 1.471901 seconds, bootstrap likelihood -9710.847575, best rearrangement setting 15
Bootstrap[16]: Time 1.259636 seconds, bootstrap likelihood -9738.589428, best rearrangement setting 12
Bootstrap[17]: Time 1.493656 seconds, bootstrap likelihood -9888.634887, best rearrangement setting 12
Bootstrap[18]: Time 1.287801 seconds, bootstrap likelihood -9927.722856, best rearrangement setting 5
Bootstrap[19]: Time 1.462025 seconds, bootstrap likelihood -9949.981609, best rearrangement setting 8
Bootstrap[20]: Time 1.682137 seconds, bootstrap likelihood -9703.926470, best rearrangement setting 10
Bootstrap[21]: Time 1.487553 seconds, bootstrap likelihood -10003.133386, best rearrangement setting 6
Bootstrap[22]: Time 1.513075 seconds, bootstrap likelihood -9476.594072, best rearrangement setting 5
Bootstrap[23]: Time 2.468830 seconds, bootstrap likelihood -10197.603552, best rearrangement setting 7
Bootstrap[24]: Time 1.460839 seconds, bootstrap likelihood -9434.641837, best rearrangement setting 8
Bootstrap[25]: Time 1.526882 seconds, bootstrap likelihood -9685.321366, best rearrangement setting 6
Bootstrap[26]: Time 1.506414 seconds, bootstrap likelihood -10077.473455, best rearrangement setting 12
Bootstrap[27]: Time 1.706024 seconds, bootstrap likelihood -9658.366452, best rearrangement setting 10
Bootstrap[28]: Time 1.540259 seconds, bootstrap likelihood -9499.925020, best rearrangement setting 11
Bootstrap[29]: Time 1.792918 seconds, bootstrap likelihood -10472.648889, best rearrangement setting 12
Bootstrap[30]: Time 1.802485 seconds, bootstrap likelihood -9624.559940, best rearrangement setting 15
Bootstrap[31]: Time 1.460118 seconds, bootstrap likelihood -9887.818221, best rearrangement setting 15
Bootstrap[32]: Time 1.353283 seconds, bootstrap likelihood -9993.307843, best rearrangement setting 6
Bootstrap[33]: Time 1.636516 seconds, bootstrap likelihood -10488.215647, best rearrangement setting 15
Bootstrap[34]: Time 1.527027 seconds, bootstrap likelihood -9732.088146, best rearrangement setting 11
Bootstrap[35]: Time 1.601031 seconds, bootstrap likelihood -10206.101939, best rearrangement setting 8
Bootstrap[36]: Time 1.538539 seconds, bootstrap likelihood -9730.241108, best rearrangement setting 9
Bootstrap[37]: Time 1.536882 seconds, bootstrap likelihood -9493.865252, best rearrangement setting 11
Bootstrap[38]: Time 1.531182 seconds, bootstrap likelihood -10064.127302, best rearrangement setting 8
Bootstrap[39]: Time 1.631997 seconds, bootstrap likelihood -9962.121130, best rearrangement setting 13
Bootstrap[40]: Time 1.486442 seconds, bootstrap likelihood -9681.960220, best rearrangement setting 13
Bootstrap[41]: Time 3.344004 seconds, bootstrap likelihood -10401.333448, best rearrangement setting 10
Bootstrap[42]: Time 1.457358 seconds, bootstrap likelihood -10595.784553, best rearrangement setting 5
Bootstrap[43]: Time 1.534346 seconds, bootstrap likelihood -9806.006446, best rearrangement setting 14
Bootstrap[44]: Time 1.534654 seconds, bootstrap likelihood -10144.318099, best rearrangement setting 10
Bootstrap[45]: Time 1.478665 seconds, bootstrap likelihood -9652.756997, best rearrangement setting 15
Bootstrap[46]: Time 1.517024 seconds, bootstrap likelihood -9664.329825, best rearrangement setting 14
Bootstrap[47]: Time 1.531533 seconds, bootstrap likelihood -9564.238046, best rearrangement setting 8
Bootstrap[48]: Time 1.593604 seconds, bootstrap likelihood -9759.302074, best rearrangement setting 6
Bootstrap[49]: Time 1.348891 seconds, bootstrap likelihood -9840.618128, best rearrangement setting 7
Bootstrap[50]: Time 1.561124 seconds, bootstrap likelihood -10223.733778, best rearrangement setting 7
Bootstrap[51]: Time 1.720448 seconds, bootstrap likelihood -10479.341165, best rearrangement setting 11
Bootstrap[52]: Time 1.473578 seconds, bootstrap likelihood -9692.615270, best rearrangement setting 12
Bootstrap[53]: Time 1.592342 seconds, bootstrap likelihood -9886.783276, best rearrangement setting 8
Bootstrap[54]: Time 1.517928 seconds, bootstrap likelihood -9849.271497, best rearrangement setting 9
Bootstrap[55]: Time 1.705651 seconds, bootstrap likelihood -9581.362965, best rearrangement setting 11
Bootstrap[56]: Time 1.295747 seconds, bootstrap likelihood -9400.747862, best rearrangement setting 5
Bootstrap[57]: Time 1.430271 seconds, bootstrap likelihood -9956.390137, best rearrangement setting 7
Bootstrap[58]: Time 1.418008 seconds, bootstrap likelihood -9724.502827, best rearrangement setting 10
Bootstrap[59]: Time 4.803571 seconds, bootstrap likelihood -9507.682085, best rearrangement setting 9
Bootstrap[60]: Time 1.709000 seconds, bootstrap likelihood -9615.092177, best rearrangement setting 7
Bootstrap[61]: Time 1.386147 seconds, bootstrap likelihood -9929.558774, best rearrangement setting 5
Bootstrap[62]: Time 1.518434 seconds, bootstrap likelihood -10071.061479, best rearrangement setting 11
Bootstrap[63]: Time 1.580021 seconds, bootstrap likelihood -9593.385202, best rearrangement setting 12
Bootstrap[64]: Time 1.353629 seconds, bootstrap likelihood -9691.143039, best rearrangement setting 7
Bootstrap[65]: Time 1.504608 seconds, bootstrap likelihood -10109.964703, best rearrangement setting 5
Bootstrap[66]: Time 1.635415 seconds, bootstrap likelihood -10078.368582, best rearrangement setting 5
Bootstrap[67]: Time 1.595407 seconds, bootstrap likelihood -9635.130630, best rearrangement setting 15
Bootstrap[68]: Time 1.417642 seconds, bootstrap likelihood -9920.120095, best rearrangement setting 11
Bootstrap[69]: Time 1.421413 seconds, bootstrap likelihood -9746.410134, best rearrangement setting 5
Bootstrap[70]: Time 1.578750 seconds, bootstrap likelihood -9479.076001, best rearrangement setting 8
Bootstrap[71]: Time 1.502580 seconds, bootstrap likelihood -9846.548338, best rearrangement setting 10
Bootstrap[72]: Time 1.577326 seconds, bootstrap likelihood -9919.053015, best rearrangement setting 11
Bootstrap[73]: Time 1.535503 seconds, bootstrap likelihood -10002.926693, best rearrangement setting 9
Bootstrap[74]: Time 1.356749 seconds, bootstrap likelihood -9681.730728, best rearrangement setting 5
Bootstrap[75]: Time 1.410362 seconds, bootstrap likelihood -9564.230868, best rearrangement setting 8
Bootstrap[76]: Time 1.483454 seconds, bootstrap likelihood -9947.302954, best rearrangement setting 9
Bootstrap[77]: Time 1.618661 seconds, bootstrap likelihood -9886.728951, best rearrangement setting 11
Bootstrap[78]: Time 1.565486 seconds, bootstrap likelihood -9470.137023, best rearrangement setting 15
Bootstrap[79]: Time 1.553095 seconds, bootstrap likelihood -9590.406848, best rearrangement setting 9
Bootstrap[80]: Time 1.489276 seconds, bootstrap likelihood -9829.105872, best rearrangement setting 15
Bootstrap[81]: Time 1.625164 seconds, bootstrap likelihood -9790.786113, best rearrangement setting 7
Bootstrap[82]: Time 1.586162 seconds, bootstrap likelihood -9397.334667, best rearrangement setting 6
Bootstrap[83]: Time 1.627817 seconds, bootstrap likelihood -9511.246695, best rearrangement setting 10
Bootstrap[84]: Time 1.891461 seconds, bootstrap likelihood -10061.142666, best rearrangement setting 11
Bootstrap[85]: Time 1.478100 seconds, bootstrap likelihood -9794.636119, best rearrangement setting 8
Bootstrap[86]: Time 1.537874 seconds, bootstrap likelihood -9849.962323, best rearrangement setting 7
Bootstrap[87]: Time 1.512280 seconds, bootstrap likelihood -10090.187766, best rearrangement setting 7
Bootstrap[88]: Time 1.583448 seconds, bootstrap likelihood -10469.536254, best rearrangement setting 12
Bootstrap[89]: Time 1.607841 seconds, bootstrap likelihood -9511.576804, best rearrangement setting 10
Bootstrap[90]: Time 1.575274 seconds, bootstrap likelihood -9821.039195, best rearrangement setting 8
Bootstrap[91]: Time 1.598615 seconds, bootstrap likelihood -9794.548287, best rearrangement setting 12
Bootstrap[92]: Time 1.654847 seconds, bootstrap likelihood -10058.549409, best rearrangement setting 13
Bootstrap[93]: Time 1.463498 seconds, bootstrap likelihood -9984.128475, best rearrangement setting 15
Bootstrap[94]: Time 1.519945 seconds, bootstrap likelihood -9761.723296, best rearrangement setting 5
Bootstrap[95]: Time 3.176804 seconds, bootstrap likelihood -9851.262397, best rearrangement setting 5
Bootstrap[96]: Time 1.629177 seconds, bootstrap likelihood -9976.099531, best rearrangement setting 13
Bootstrap[97]: Time 1.800648 seconds, bootstrap likelihood -10334.183695, best rearrangement setting 11
Bootstrap[98]: Time 1.522773 seconds, bootstrap likelihood -9057.659280, best rearrangement setting 6
Bootstrap[99]: Time 1.533961 seconds, bootstrap likelihood -9911.675172, best rearrangement setting 14
Bootstrap[100]: Time 1.583152 seconds, bootstrap likelihood -10141.746588, best rearrangement setting 12
Bootstrap[101]: Time 1.419477 seconds, bootstrap likelihood -9800.676907, best rearrangement setting 10
Bootstrap[102]: Time 1.579157 seconds, bootstrap likelihood -10187.166108, best rearrangement setting 8
Bootstrap[103]: Time 1.470340 seconds, bootstrap likelihood -9751.780045, best rearrangement setting 8
Bootstrap[104]: Time 1.528899 seconds, bootstrap likelihood -10318.835369, best rearrangement setting 15
Bootstrap[105]: Time 1.593900 seconds, bootstrap likelihood -10591.409366, best rearrangement setting 7
Bootstrap[106]: Time 1.584567 seconds, bootstrap likelihood -9478.724404, best rearrangement setting 6
Bootstrap[107]: Time 1.682814 seconds, bootstrap likelihood -10020.917256, best rearrangement setting 13
Bootstrap[108]: Time 1.539904 seconds, bootstrap likelihood -9554.668877, best rearrangement setting 14
Bootstrap[109]: Time 1.548120 seconds, bootstrap likelihood -10004.445395, best rearrangement setting 12
Bootstrap[110]: Time 1.533403 seconds, bootstrap likelihood -9692.945078, best rearrangement setting 7
Bootstrap[111]: Time 1.285420 seconds, bootstrap likelihood -9197.220974, best rearrangement setting 15
Bootstrap[112]: Time 1.691680 seconds, bootstrap likelihood -9555.281001, best rearrangement setting 14
Bootstrap[113]: Time 3.401608 seconds, bootstrap likelihood -9709.905090, best rearrangement setting 5
Bootstrap[114]: Time 1.478674 seconds, bootstrap likelihood -9870.550517, best rearrangement setting 6
Bootstrap[115]: Time 1.461218 seconds, bootstrap likelihood -9807.753464, best rearrangement setting 7
Bootstrap[116]: Time 1.438488 seconds, bootstrap likelihood -9785.688478, best rearrangement setting 11
Bootstrap[117]: Time 1.748789 seconds, bootstrap likelihood -9482.242684, best rearrangement setting 8
Bootstrap[118]: Time 1.569984 seconds, bootstrap likelihood -10005.898845, best rearrangement setting 9
Bootstrap[119]: Time 1.625718 seconds, bootstrap likelihood -10392.320900, best rearrangement setting 14
Bootstrap[120]: Time 1.725046 seconds, bootstrap likelihood -10182.499355, best rearrangement setting 12
Bootstrap[121]: Time 1.542811 seconds, bootstrap likelihood -9161.864797, best rearrangement setting 8
Bootstrap[122]: Time 1.428545 seconds, bootstrap likelihood -9578.454640, best rearrangement setting 9
Bootstrap[123]: Time 1.243031 seconds, bootstrap likelihood -9488.739175, best rearrangement setting 6
Bootstrap[124]: Time 1.659567 seconds, bootstrap likelihood -10072.143179, best rearrangement setting 11
Bootstrap[125]: Time 1.605272 seconds, bootstrap likelihood -10169.743499, best rearrangement setting 11
Bootstrap[126]: Time 1.742342 seconds, bootstrap likelihood -10072.851337, best rearrangement setting 12
Bootstrap[127]: Time 1.562286 seconds, bootstrap likelihood -10154.892518, best rearrangement setting 9
Bootstrap[128]: Time 1.417113 seconds, bootstrap likelihood -9478.517465, best rearrangement setting 11
Bootstrap[129]: Time 1.467893 seconds, bootstrap likelihood -10028.473111, best rearrangement setting 5
Bootstrap[130]: Time 1.696165 seconds, bootstrap likelihood -10575.348556, best rearrangement setting 10
Bootstrap[131]: Time 3.456744 seconds, bootstrap likelihood -10067.885455, best rearrangement setting 9
Bootstrap[132]: Time 1.562684 seconds, bootstrap likelihood -9878.685278, best rearrangement setting 14
Bootstrap[133]: Time 1.504810 seconds, bootstrap likelihood -9302.191379, best rearrangement setting 13
Bootstrap[134]: Time 1.402002 seconds, bootstrap likelihood -9745.744827, best rearrangement setting 6
Bootstrap[135]: Time 1.638052 seconds, bootstrap likelihood -10393.080042, best rearrangement setting 11
Bootstrap[136]: Time 1.542778 seconds, bootstrap likelihood -9489.719936, best rearrangement setting 13
Bootstrap[137]: Time 1.439028 seconds, bootstrap likelihood -9409.516160, best rearrangement setting 6
Bootstrap[138]: Time 1.500685 seconds, bootstrap likelihood -9637.992319, best rearrangement setting 15
Bootstrap[139]: Time 1.500775 seconds, bootstrap likelihood -9429.784948, best rearrangement setting 5
Bootstrap[140]: Time 1.760362 seconds, bootstrap likelihood -10456.270774, best rearrangement setting 13
Bootstrap[141]: Time 1.215280 seconds, bootstrap likelihood -9735.478171, best rearrangement setting 5
Bootstrap[142]: Time 1.395194 seconds, bootstrap likelihood -9473.840283, best rearrangement setting 15
Bootstrap[143]: Time 1.343171 seconds, bootstrap likelihood -9941.187045, best rearrangement setting 7
Bootstrap[144]: Time 1.609316 seconds, bootstrap likelihood -9216.771760, best rearrangement setting 13
Bootstrap[145]: Time 1.576600 seconds, bootstrap likelihood -9707.498744, best rearrangement setting 7
Bootstrap[146]: Time 1.640819 seconds, bootstrap likelihood -9571.213624, best rearrangement setting 9
Bootstrap[147]: Time 1.745649 seconds, bootstrap likelihood -10136.461994, best rearrangement setting 12
Bootstrap[148]: Time 1.486796 seconds, bootstrap likelihood -9629.346424, best rearrangement setting 8
Bootstrap[149]: Time 4.133852 seconds, bootstrap likelihood -9756.153495, best rearrangement setting 12
Bootstrap[150]: Time 1.486023 seconds, bootstrap likelihood -9699.337120, best rearrangement setting 14
Bootstrap[151]: Time 1.381526 seconds, bootstrap likelihood -9657.303094, best rearrangement setting 5
Bootstrap[152]: Time 1.311539 seconds, bootstrap likelihood -9583.044904, best rearrangement setting 5
Bootstrap[153]: Time 1.556251 seconds, bootstrap likelihood -10098.313624, best rearrangement setting 13
Bootstrap[154]: Time 1.546443 seconds, bootstrap likelihood -9676.149045, best rearrangement setting 14
Bootstrap[155]: Time 1.559395 seconds, bootstrap likelihood -9709.014115, best rearrangement setting 13
Bootstrap[156]: Time 1.481166 seconds, bootstrap likelihood -9572.170360, best rearrangement setting 11
Bootstrap[157]: Time 1.738755 seconds, bootstrap likelihood -10114.125506, best rearrangement setting 8
Bootstrap[158]: Time 1.536243 seconds, bootstrap likelihood -9701.953895, best rearrangement setting 8
Bootstrap[159]: Time 1.314309 seconds, bootstrap likelihood -9485.921414, best rearrangement setting 5
Bootstrap[160]: Time 1.470295 seconds, bootstrap likelihood -9691.523464, best rearrangement setting 15
Bootstrap[161]: Time 1.476938 seconds, bootstrap likelihood -9456.313173, best rearrangement setting 13
Bootstrap[162]: Time 1.415248 seconds, bootstrap likelihood -9932.394299, best rearrangement setting 13
Bootstrap[163]: Time 1.574629 seconds, bootstrap likelihood -9872.055612, best rearrangement setting 12
Bootstrap[164]: Time 1.435245 seconds, bootstrap likelihood -10104.620617, best rearrangement setting 7
Bootstrap[165]: Time 1.579458 seconds, bootstrap likelihood -9886.089393, best rearrangement setting 13
Bootstrap[166]: Time 1.705759 seconds, bootstrap likelihood -9534.940077, best rearrangement setting 10
Bootstrap[167]: Time 1.610728 seconds, bootstrap likelihood -9458.154525, best rearrangement setting 12
Bootstrap[168]: Time 1.483297 seconds, bootstrap likelihood -10167.268509, best rearrangement setting 14
Bootstrap[169]: Time 1.491602 seconds, bootstrap likelihood -9249.532068, best rearrangement setting 10
Bootstrap[170]: Time 1.618029 seconds, bootstrap likelihood -9031.535080, best rearrangement setting 5
Bootstrap[171]: Time 1.592229 seconds, bootstrap likelihood -10279.536200, best rearrangement setting 11
Bootstrap[172]: Time 1.533191 seconds, bootstrap likelihood -9460.255055, best rearrangement setting 12
Bootstrap[173]: Time 1.397912 seconds, bootstrap likelihood -9529.351061, best rearrangement setting 11
Bootstrap[174]: Time 1.688100 seconds, bootstrap likelihood -9586.918746, best rearrangement setting 15
Bootstrap[175]: Time 1.604047 seconds, bootstrap likelihood -9765.823942, best rearrangement setting 14
Bootstrap[176]: Time 1.721952 seconds, bootstrap likelihood -9494.111718, best rearrangement setting 8
Bootstrap[177]: Time 1.549600 seconds, bootstrap likelihood -10192.561803, best rearrangement setting 8
Bootstrap[178]: Time 1.581442 seconds, bootstrap likelihood -9332.209046, best rearrangement setting 14
Bootstrap[179]: Time 1.363862 seconds, bootstrap likelihood -9367.269695, best rearrangement setting 5
Bootstrap[180]: Time 1.574279 seconds, bootstrap likelihood -10443.544392, best rearrangement setting 12
Bootstrap[181]: Time 1.632955 seconds, bootstrap likelihood -9881.042928, best rearrangement setting 14
Bootstrap[182]: Time 1.631189 seconds, bootstrap likelihood -9956.858096, best rearrangement setting 7
Bootstrap[183]: Time 1.389006 seconds, bootstrap likelihood -9635.288770, best rearrangement setting 11
Bootstrap[184]: Time 1.943116 seconds, bootstrap likelihood -9316.445940, best rearrangement setting 15
Bootstrap[185]: Time 1.845944 seconds, bootstrap likelihood -10122.161867, best rearrangement setting 8
Bootstrap[186]: Time 1.471796 seconds, bootstrap likelihood -9408.064171, best rearrangement setting 13
Bootstrap[187]: Time 1.478105 seconds, bootstrap likelihood -9324.089138, best rearrangement setting 8
Bootstrap[188]: Time 1.360665 seconds, bootstrap likelihood -9921.957799, best rearrangement setting 12
Bootstrap[189]: Time 1.558032 seconds, bootstrap likelihood -9881.715512, best rearrangement setting 11
Bootstrap[190]: Time 1.567984 seconds, bootstrap likelihood -10009.867050, best rearrangement setting 15
Bootstrap[191]: Time 1.571178 seconds, bootstrap likelihood -9823.780069, best rearrangement setting 8
Bootstrap[192]: Time 1.332687 seconds, bootstrap likelihood -9647.881333, best rearrangement setting 8
Bootstrap[193]: Time 1.657728 seconds, bootstrap likelihood -10194.858899, best rearrangement setting 10
Bootstrap[194]: Time 1.704562 seconds, bootstrap likelihood -9777.667529, best rearrangement setting 8
Bootstrap[195]: Time 1.524193 seconds, bootstrap likelihood -10038.779606, best rearrangement setting 7
Bootstrap[196]: Time 1.645192 seconds, bootstrap likelihood -9851.683440, best rearrangement setting 11
Bootstrap[197]: Time 1.460399 seconds, bootstrap likelihood -9875.690618, best rearrangement setting 8
Bootstrap[198]: Time 1.390516 seconds, bootstrap likelihood -9699.397682, best rearrangement setting 15
Bootstrap[199]: Time 1.544587 seconds, bootstrap likelihood -9629.544128, best rearrangement setting 8
Bootstrap[200]: Time 1.666760 seconds, bootstrap likelihood -9864.130864, best rearrangement setting 12
Bootstrap[201]: Time 1.529897 seconds, bootstrap likelihood -9616.737411, best rearrangement setting 10
Bootstrap[202]: Time 1.816237 seconds, bootstrap likelihood -9513.430228, best rearrangement setting 12
Bootstrap[203]: Time 3.581356 seconds, bootstrap likelihood -10279.145210, best rearrangement setting 9
Bootstrap[204]: Time 1.599073 seconds, bootstrap likelihood -9709.190014, best rearrangement setting 7
Bootstrap[205]: Time 1.406105 seconds, bootstrap likelihood -9735.619538, best rearrangement setting 8
Bootstrap[206]: Time 1.652201 seconds, bootstrap likelihood -9834.883694, best rearrangement setting 15
Bootstrap[207]: Time 1.586355 seconds, bootstrap likelihood -9871.505068, best rearrangement setting 10
Bootstrap[208]: Time 1.527955 seconds, bootstrap likelihood -9794.899706, best rearrangement setting 15
Bootstrap[209]: Time 1.498442 seconds, bootstrap likelihood -10180.434937, best rearrangement setting 15
Bootstrap[210]: Time 1.437991 seconds, bootstrap likelihood -10444.481067, best rearrangement setting 8
Bootstrap[211]: Time 1.380175 seconds, bootstrap likelihood -8923.697434, best rearrangement setting 8
Bootstrap[212]: Time 1.370568 seconds, bootstrap likelihood -10211.517689, best rearrangement setting 5
Bootstrap[213]: Time 1.391490 seconds, bootstrap likelihood -10236.294730, best rearrangement setting 6
Bootstrap[214]: Time 1.641279 seconds, bootstrap likelihood -9801.287177, best rearrangement setting 13
Bootstrap[215]: Time 1.612445 seconds, bootstrap likelihood -10090.696444, best rearrangement setting 6
Bootstrap[216]: Time 1.604595 seconds, bootstrap likelihood -9238.319875, best rearrangement setting 13
Bootstrap[217]: Time 1.459642 seconds, bootstrap likelihood -9108.120130, best rearrangement setting 8
Bootstrap[218]: Time 1.695855 seconds, bootstrap likelihood -9858.026156, best rearrangement setting 12
Bootstrap[219]: Time 1.536677 seconds, bootstrap likelihood -9194.645643, best rearrangement setting 6
Bootstrap[220]: Time 1.532644 seconds, bootstrap likelihood -9494.116341, best rearrangement setting 8
Bootstrap[221]: Time 4.104172 seconds, bootstrap likelihood -9436.927519, best rearrangement setting 13
Bootstrap[222]: Time 1.524978 seconds, bootstrap likelihood -10094.195847, best rearrangement setting 6
Bootstrap[223]: Time 1.877450 seconds, bootstrap likelihood -9622.132220, best rearrangement setting 10
Bootstrap[224]: Time 1.714198 seconds, bootstrap likelihood -10031.550217, best rearrangement setting 11
Bootstrap[225]: Time 1.696430 seconds, bootstrap likelihood -9944.587582, best rearrangement setting 13
Bootstrap[226]: Time 1.430878 seconds, bootstrap likelihood -9674.099723, best rearrangement setting 7
Bootstrap[227]: Time 1.509498 seconds, bootstrap likelihood -9401.345030, best rearrangement setting 9
Bootstrap[228]: Time 1.721739 seconds, bootstrap likelihood -10027.986479, best rearrangement setting 13
Bootstrap[229]: Time 1.444322 seconds, bootstrap likelihood -9832.974103, best rearrangement setting 9
Bootstrap[230]: Time 1.517305 seconds, bootstrap likelihood -9858.009725, best rearrangement setting 15
Bootstrap[231]: Time 1.599006 seconds, bootstrap likelihood -9859.944215, best rearrangement setting 12
Bootstrap[232]: Time 1.604515 seconds, bootstrap likelihood -9634.002654, best rearrangement setting 15
Bootstrap[233]: Time 1.525134 seconds, bootstrap likelihood -9724.518011, best rearrangement setting 12
Bootstrap[234]: Time 1.416302 seconds, bootstrap likelihood -9626.084386, best rearrangement setting 6
Bootstrap[235]: Time 1.482104 seconds, bootstrap likelihood -9770.637415, best rearrangement setting 15
Bootstrap[236]: Time 1.619047 seconds, bootstrap likelihood -9294.912050, best rearrangement setting 9
Bootstrap[237]: Time 1.568775 seconds, bootstrap likelihood -9758.266068, best rearrangement setting 5
Bootstrap[238]: Time 4.712050 seconds, bootstrap likelihood -10546.963375, best rearrangement setting 11
Bootstrap[239]: Time 1.718188 seconds, bootstrap likelihood -9618.832211, best rearrangement setting 14
Bootstrap[240]: Time 1.550629 seconds, bootstrap likelihood -9729.325282, best rearrangement setting 13
Bootstrap[241]: Time 1.593140 seconds, bootstrap likelihood -10005.734884, best rearrangement setting 13
Bootstrap[242]: Time 1.545603 seconds, bootstrap likelihood -9593.555318, best rearrangement setting 9
Bootstrap[243]: Time 1.571613 seconds, bootstrap likelihood -9990.497050, best rearrangement setting 14
Bootstrap[244]: Time 1.401574 seconds, bootstrap likelihood -9735.646419, best rearrangement setting 5
Bootstrap[245]: Time 1.490424 seconds, bootstrap likelihood -10008.328875, best rearrangement setting 6
Bootstrap[246]: Time 1.465276 seconds, bootstrap likelihood -9533.762765, best rearrangement setting 5
Bootstrap[247]: Time 1.432062 seconds, bootstrap likelihood -9198.804547, best rearrangement setting 13
Bootstrap[248]: Time 1.552988 seconds, bootstrap likelihood -9405.943036, best rearrangement setting 10
Bootstrap[249]: Time 1.561833 seconds, bootstrap likelihood -10193.178588, best rearrangement setting 7
Bootstrap[250]: Time 1.613794 seconds, bootstrap likelihood -9861.543818, best rearrangement setting 7
Bootstrap[251]: Time 1.627780 seconds, bootstrap likelihood -9848.286827, best rearrangement setting 15
Bootstrap[252]: Time 1.383527 seconds, bootstrap likelihood -9957.011980, best rearrangement setting 6
Bootstrap[253]: Time 1.593351 seconds, bootstrap likelihood -9532.662691, best rearrangement setting 9
Bootstrap[254]: Time 1.612391 seconds, bootstrap likelihood -9508.878850, best rearrangement setting 9
Bootstrap[255]: Time 1.382502 seconds, bootstrap likelihood -9704.773099, best rearrangement setting 8
Bootstrap[256]: Time 1.554707 seconds, bootstrap likelihood -9284.777116, best rearrangement setting 15
Bootstrap[257]: Time 1.578334 seconds, bootstrap likelihood -9591.679960, best rearrangement setting 9
Bootstrap[258]: Time 1.433350 seconds, bootstrap likelihood -9709.227990, best rearrangement setting 11
Bootstrap[259]: Time 1.393860 seconds, bootstrap likelihood -9613.325301, best rearrangement setting 12
Bootstrap[260]: Time 1.283462 seconds, bootstrap likelihood -9794.959263, best rearrangement setting 6
Bootstrap[261]: Time 1.460063 seconds, bootstrap likelihood -9990.044101, best rearrangement setting 5
Bootstrap[262]: Time 1.558115 seconds, bootstrap likelihood -9604.264667, best rearrangement setting 10
Bootstrap[263]: Time 1.517182 seconds, bootstrap likelihood -9595.529134, best rearrangement setting 13
Bootstrap[264]: Time 1.490961 seconds, bootstrap likelihood -9787.988797, best rearrangement setting 11
Bootstrap[265]: Time 1.450161 seconds, bootstrap likelihood -9860.493155, best rearrangement setting 10
Bootstrap[266]: Time 1.561982 seconds, bootstrap likelihood -9985.457303, best rearrangement setting 7
Bootstrap[267]: Time 1.620461 seconds, bootstrap likelihood -9312.173212, best rearrangement setting 11
Bootstrap[268]: Time 1.217133 seconds, bootstrap likelihood -9360.977140, best rearrangement setting 12
Bootstrap[269]: Time 1.694808 seconds, bootstrap likelihood -9525.759153, best rearrangement setting 14
Bootstrap[270]: Time 1.482177 seconds, bootstrap likelihood -9875.235177, best rearrangement setting 6
Bootstrap[271]: Time 1.726879 seconds, bootstrap likelihood -9838.884553, best rearrangement setting 11
Bootstrap[272]: Time 1.116654 seconds, bootstrap likelihood -9709.478310, best rearrangement setting 5
Bootstrap[273]: Time 1.257859 seconds, bootstrap likelihood -9676.795691, best rearrangement setting 10
Bootstrap[274]: Time 1.505801 seconds, bootstrap likelihood -9608.924513, best rearrangement setting 9
Bootstrap[275]: Time 3.602027 seconds, bootstrap likelihood -10127.352707, best rearrangement setting 12
Bootstrap[276]: Time 1.560284 seconds, bootstrap likelihood -9942.355599, best rearrangement setting 10
Bootstrap[277]: Time 1.536719 seconds, bootstrap likelihood -10293.435010, best rearrangement setting 8
Bootstrap[278]: Time 1.579738 seconds, bootstrap likelihood -9786.593673, best rearrangement setting 14
Bootstrap[279]: Time 1.364882 seconds, bootstrap likelihood -9379.880666, best rearrangement setting 5
Bootstrap[280]: Time 1.485959 seconds, bootstrap likelihood -9142.347491, best rearrangement setting 7
Bootstrap[281]: Time 1.604088 seconds, bootstrap likelihood -10204.718110, best rearrangement setting 10
Bootstrap[282]: Time 1.700001 seconds, bootstrap likelihood -10093.137719, best rearrangement setting 12
Bootstrap[283]: Time 1.436771 seconds, bootstrap likelihood -9777.321275, best rearrangement setting 7
Bootstrap[284]: Time 1.536111 seconds, bootstrap likelihood -10192.873467, best rearrangement setting 5
Bootstrap[285]: Time 1.649753 seconds, bootstrap likelihood -9717.896314, best rearrangement setting 6
Bootstrap[286]: Time 1.744899 seconds, bootstrap likelihood -9999.882384, best rearrangement setting 15
Bootstrap[287]: Time 1.361635 seconds, bootstrap likelihood -9476.963479, best rearrangement setting 5
Bootstrap[288]: Time 1.686053 seconds, bootstrap likelihood -9798.142492, best rearrangement setting 13
Bootstrap[289]: Time 1.609235 seconds, bootstrap likelihood -9649.111462, best rearrangement setting 6
Bootstrap[290]: Time 1.283422 seconds, bootstrap likelihood -9504.002575, best rearrangement setting 7
Bootstrap[291]: Time 1.452114 seconds, bootstrap likelihood -10116.118606, best rearrangement setting 11
Bootstrap[292]: Time 1.368086 seconds, bootstrap likelihood -9723.498794, best rearrangement setting 6
Bootstrap[293]: Time 3.983742 seconds, bootstrap likelihood -10089.876070, best rearrangement setting 8
Bootstrap[294]: Time 1.339149 seconds, bootstrap likelihood -9516.984780, best rearrangement setting 12
Bootstrap[295]: Time 1.472360 seconds, bootstrap likelihood -9741.206069, best rearrangement setting 15
Bootstrap[296]: Time 1.530408 seconds, bootstrap likelihood -9556.040770, best rearrangement setting 14
Bootstrap[297]: Time 1.442914 seconds, bootstrap likelihood -9235.764358, best rearrangement setting 10
Bootstrap[298]: Time 1.738218 seconds, bootstrap likelihood -10267.019281, best rearrangement setting 13
Bootstrap[299]: Time 1.558188 seconds, bootstrap likelihood -9860.684765, best rearrangement setting 13
Bootstrap[300]: Time 1.574156 seconds, bootstrap likelihood -9254.560389, best rearrangement setting 11
Bootstrap[301]: Time 1.677764 seconds, bootstrap likelihood -9818.630674, best rearrangement setting 15
Bootstrap[302]: Time 1.625653 seconds, bootstrap likelihood -10281.824530, best rearrangement setting 13
Bootstrap[303]: Time 1.680545 seconds, bootstrap likelihood -9788.460722, best rearrangement setting 11
Bootstrap[304]: Time 1.668977 seconds, bootstrap likelihood -10071.669643, best rearrangement setting 9
Bootstrap[305]: Time 1.496308 seconds, bootstrap likelihood -9452.263613, best rearrangement setting 5
Bootstrap[306]: Time 1.240328 seconds, bootstrap likelihood -9828.382822, best rearrangement setting 12
Bootstrap[307]: Time 1.562905 seconds, bootstrap likelihood -9532.875624, best rearrangement setting 9
Bootstrap[308]: Time 1.709119 seconds, bootstrap likelihood -9971.011488, best rearrangement setting 11
Bootstrap[309]: Time 1.722914 seconds, bootstrap likelihood -9273.159925, best rearrangement setting 9
Bootstrap[310]: Time 1.421156 seconds, bootstrap likelihood -9672.979409, best rearrangement setting 7
Bootstrap[311]: Time 3.441176 seconds, bootstrap likelihood -9976.442391, best rearrangement setting 7
Bootstrap[312]: Time 1.391950 seconds, bootstrap likelihood -9492.873254, best rearrangement setting 8
Bootstrap[313]: Time 1.396424 seconds, bootstrap likelihood -9382.676700, best rearrangement setting 13
Bootstrap[314]: Time 1.602108 seconds, bootstrap likelihood -9803.149128, best rearrangement setting 8
Bootstrap[315]: Time 1.379209 seconds, bootstrap likelihood -10107.702617, best rearrangement setting 5
Bootstrap[316]: Time 1.369182 seconds, bootstrap likelihood -9233.934905, best rearrangement setting 10
Bootstrap[317]: Time 1.693363 seconds, bootstrap likelihood -9279.335115, best rearrangement setting 10
Bootstrap[318]: Time 1.445522 seconds, bootstrap likelihood -9275.350772, best rearrangement setting 14
Bootstrap[319]: Time 1.463222 seconds, bootstrap likelihood -9498.219365, best rearrangement setting 10
Bootstrap[320]: Time 1.802195 seconds, bootstrap likelihood -10755.136847, best rearrangement setting 13
Bootstrap[321]: Time 1.415019 seconds, bootstrap likelihood -9707.325015, best rearrangement setting 13
Bootstrap[322]: Time 1.464408 seconds, bootstrap likelihood -9673.347099, best rearrangement setting 13
Bootstrap[323]: Time 1.581135 seconds, bootstrap likelihood -9908.927454, best rearrangement setting 14
Bootstrap[324]: Time 1.487672 seconds, bootstrap likelihood -9814.798816, best rearrangement setting 12
Bootstrap[325]: Time 1.608054 seconds, bootstrap likelihood -9972.667068, best rearrangement setting 9
Bootstrap[326]: Time 1.690415 seconds, bootstrap likelihood -10092.189736, best rearrangement setting 8
Bootstrap[327]: Time 1.422397 seconds, bootstrap likelihood -10048.602025, best rearrangement setting 7
Bootstrap[328]: Time 1.643077 seconds, bootstrap likelihood -9856.568727, best rearrangement setting 9
Bootstrap[329]: Time 4.131011 seconds, bootstrap likelihood -9993.632674, best rearrangement setting 8
Bootstrap[330]: Time 1.506158 seconds, bootstrap likelihood -9609.592929, best rearrangement setting 8
Bootstrap[331]: Time 1.493832 seconds, bootstrap likelihood -10132.707589, best rearrangement setting 13
Bootstrap[332]: Time 1.641199 seconds, bootstrap likelihood -9879.834277, best rearrangement setting 5
Bootstrap[333]: Time 1.443247 seconds, bootstrap likelihood -9351.685012, best rearrangement setting 9
Bootstrap[334]: Time 1.553838 seconds, bootstrap likelihood -9762.987492, best rearrangement setting 11
Bootstrap[335]: Time 1.657195 seconds, bootstrap likelihood -9785.727182, best rearrangement setting 13
Bootstrap[336]: Time 1.615629 seconds, bootstrap likelihood -9893.403718, best rearrangement setting 14
Bootstrap[337]: Time 1.287718 seconds, bootstrap likelihood -9345.398433, best rearrangement setting 6
Bootstrap[338]: Time 1.580328 seconds, bootstrap likelihood -10035.790088, best rearrangement setting 7
Bootstrap[339]: Time 1.448057 seconds, bootstrap likelihood -9439.878370, best rearrangement setting 6
Bootstrap[340]: Time 1.422690 seconds, bootstrap likelihood -10346.291245, best rearrangement setting 15
Bootstrap[341]: Time 1.387075 seconds, bootstrap likelihood -9982.698447, best rearrangement setting 5
Bootstrap[342]: Time 1.429267 seconds, bootstrap likelihood -9655.058643, best rearrangement setting 13
Bootstrap[343]: Time 1.218525 seconds, bootstrap likelihood -9645.909224, best rearrangement setting 5
Bootstrap[344]: Time 1.741587 seconds, bootstrap likelihood -9875.356298, best rearrangement setting 12
Bootstrap[345]: Time 1.472442 seconds, bootstrap likelihood -9694.982810, best rearrangement setting 11
Bootstrap[346]: Time 1.476357 seconds, bootstrap likelihood -9915.274711, best rearrangement setting 6
Bootstrap[347]: Time 1.729671 seconds, bootstrap likelihood -9784.217180, best rearrangement setting 12
Bootstrap[348]: Time 1.228649 seconds, bootstrap likelihood -9764.015618, best rearrangement setting 5
Bootstrap[349]: Time 1.313368 seconds, bootstrap likelihood -9979.902653, best rearrangement setting 7
Bootstrap[350]: Time 1.359881 seconds, bootstrap likelihood -10393.844733, best rearrangement setting 6
Bootstrap[351]: Time 1.290315 seconds, bootstrap likelihood -9158.519953, best rearrangement setting 6
Bootstrap[352]: Time 1.298284 seconds, bootstrap likelihood -9697.349122, best rearrangement setting 7
Bootstrap[353]: Time 1.677392 seconds, bootstrap likelihood -9429.016747, best rearrangement setting 7
Bootstrap[354]: Time 1.593039 seconds, bootstrap likelihood -10079.615295, best rearrangement setting 11
Bootstrap[355]: Time 1.495229 seconds, bootstrap likelihood -9621.403234, best rearrangement setting 14
Bootstrap[356]: Time 1.564056 seconds, bootstrap likelihood -10001.876202, best rearrangement setting 15
Bootstrap[357]: Time 1.737176 seconds, bootstrap likelihood -9686.669834, best rearrangement setting 11
Bootstrap[358]: Time 1.732448 seconds, bootstrap likelihood -9891.249891, best rearrangement setting 14
Bootstrap[359]: Time 1.401152 seconds, bootstrap likelihood -9711.589556, best rearrangement setting 6
Bootstrap[360]: Time 1.508803 seconds, bootstrap likelihood -10029.576857, best rearrangement setting 6
Bootstrap[361]: Time 1.544542 seconds, bootstrap likelihood -9627.449421, best rearrangement setting 10
Bootstrap[362]: Time 1.678667 seconds, bootstrap likelihood -10036.106554, best rearrangement setting 8
Bootstrap[363]: Time 1.590058 seconds, bootstrap likelihood -10011.222632, best rearrangement setting 10
Bootstrap[364]: Time 1.725726 seconds, bootstrap likelihood -10347.006171, best rearrangement setting 9
Bootstrap[365]: Time 4.247095 seconds, bootstrap likelihood -9809.065743, best rearrangement setting 10
Bootstrap[366]: Time 1.606777 seconds, bootstrap likelihood -10143.745104, best rearrangement setting 8
Bootstrap[367]: Time 1.366728 seconds, bootstrap likelihood -9776.595806, best rearrangement setting 5
Bootstrap[368]: Time 1.528211 seconds, bootstrap likelihood -9898.690678, best rearrangement setting 11
Bootstrap[369]: Time 1.578236 seconds, bootstrap likelihood -9447.614659, best rearrangement setting 13
Bootstrap[370]: Time 1.702799 seconds, bootstrap likelihood -10193.814873, best rearrangement setting 13
Bootstrap[371]: Time 1.662644 seconds, bootstrap likelihood -9455.120917, best rearrangement setting 12
Bootstrap[372]: Time 1.828670 seconds, bootstrap likelihood -9956.438796, best rearrangement setting 10
Bootstrap[373]: Time 1.692262 seconds, bootstrap likelihood -9705.464368, best rearrangement setting 15
Bootstrap[374]: Time 1.401299 seconds, bootstrap likelihood -9453.067497, best rearrangement setting 5
Bootstrap[375]: Time 1.608666 seconds, bootstrap likelihood -10296.331846, best rearrangement setting 15
Bootstrap[376]: Time 1.455048 seconds, bootstrap likelihood -9604.576230, best rearrangement setting 7
Bootstrap[377]: Time 1.434209 seconds, bootstrap likelihood -9663.480034, best rearrangement setting 12
Bootstrap[378]: Time 1.569495 seconds, bootstrap likelihood -9877.889782, best rearrangement setting 13
Bootstrap[379]: Time 1.718547 seconds, bootstrap likelihood -9773.883743, best rearrangement setting 9
Bootstrap[380]: Time 1.621849 seconds, bootstrap likelihood -9553.999128, best rearrangement setting 10
Bootstrap[381]: Time 1.282701 seconds, bootstrap likelihood -9622.953235, best rearrangement setting 6
Bootstrap[382]: Time 1.511557 seconds, bootstrap likelihood -9590.714345, best rearrangement setting 8
Bootstrap[383]: Time 1.491074 seconds, bootstrap likelihood -9772.242364, best rearrangement setting 15
Bootstrap[384]: Time 1.469831 seconds, bootstrap likelihood -10273.160889, best rearrangement setting 10
Bootstrap[385]: Time 1.597106 seconds, bootstrap likelihood -9685.710534, best rearrangement setting 10
Bootstrap[386]: Time 1.464485 seconds, bootstrap likelihood -9508.486598, best rearrangement setting 15
Bootstrap[387]: Time 1.749150 seconds, bootstrap likelihood -9832.142533, best rearrangement setting 12
Bootstrap[388]: Time 1.564116 seconds, bootstrap likelihood -9583.538909, best rearrangement setting 10
Bootstrap[389]: Time 1.488347 seconds, bootstrap likelihood -9221.930255, best rearrangement setting 6
Bootstrap[390]: Time 1.624416 seconds, bootstrap likelihood -9650.664541, best rearrangement setting 14
Bootstrap[391]: Time 1.545490 seconds, bootstrap likelihood -9949.055267, best rearrangement setting 13
Bootstrap[392]: Time 1.708269 seconds, bootstrap likelihood -10147.274108, best rearrangement setting 7
Bootstrap[393]: Time 1.569102 seconds, bootstrap likelihood -9987.422638, best rearrangement setting 13
Bootstrap[394]: Time 1.517270 seconds, bootstrap likelihood -9713.591963, best rearrangement setting 15
Bootstrap[395]: Time 1.303577 seconds, bootstrap likelihood -9604.364068, best rearrangement setting 8
Bootstrap[396]: Time 1.545264 seconds, bootstrap likelihood -9344.198974, best rearrangement setting 7
Bootstrap[397]: Time 1.511555 seconds, bootstrap likelihood -10031.123504, best rearrangement setting 11
Bootstrap[398]: Time 1.591082 seconds, bootstrap likelihood -9081.453140, best rearrangement setting 11
Bootstrap[399]: Time 1.656536 seconds, bootstrap likelihood -9409.854854, best rearrangement setting 8
Bootstrap[400]: Time 1.397061 seconds, bootstrap likelihood -9641.957294, best rearrangement setting 5
Bootstrap[401]: Time 3.627993 seconds, bootstrap likelihood -9403.041671, best rearrangement setting 15
Bootstrap[402]: Time 1.420167 seconds, bootstrap likelihood -9550.117624, best rearrangement setting 5
Bootstrap[403]: Time 1.491079 seconds, bootstrap likelihood -9701.516610, best rearrangement setting 5
Bootstrap[404]: Time 1.546526 seconds, bootstrap likelihood -10073.867872, best rearrangement setting 6
Bootstrap[405]: Time 1.646869 seconds, bootstrap likelihood -9637.101720, best rearrangement setting 15
Bootstrap[406]: Time 1.497814 seconds, bootstrap likelihood -9873.506908, best rearrangement setting 9
Bootstrap[407]: Time 1.588186 seconds, bootstrap likelihood -9856.446105, best rearrangement setting 12
Bootstrap[408]: Time 1.600659 seconds, bootstrap likelihood -9805.379480, best rearrangement setting 9
Bootstrap[409]: Time 1.678011 seconds, bootstrap likelihood -9459.672740, best rearrangement setting 13
Bootstrap[410]: Time 1.719950 seconds, bootstrap likelihood -10066.583903, best rearrangement setting 15
Bootstrap[411]: Time 1.646640 seconds, bootstrap likelihood -10182.472315, best rearrangement setting 14
Bootstrap[412]: Time 1.463040 seconds, bootstrap likelihood -9870.257216, best rearrangement setting 7
Bootstrap[413]: Time 1.437321 seconds, bootstrap likelihood -9416.007155, best rearrangement setting 5
Bootstrap[414]: Time 1.519503 seconds, bootstrap likelihood -9544.480439, best rearrangement setting 6
Bootstrap[415]: Time 1.480653 seconds, bootstrap likelihood -9648.498429, best rearrangement setting 9
Bootstrap[416]: Time 1.414477 seconds, bootstrap likelihood -10058.194359, best rearrangement setting 6
Bootstrap[417]: Time 1.480903 seconds, bootstrap likelihood -9611.312158, best rearrangement setting 10
Bootstrap[418]: Time 1.551763 seconds, bootstrap likelihood -9883.426768, best rearrangement setting 15
Bootstrap[419]: Time 3.833424 seconds, bootstrap likelihood -9961.081954, best rearrangement setting 14
Bootstrap[420]: Time 1.474505 seconds, bootstrap likelihood -9706.678476, best rearrangement setting 5
Bootstrap[421]: Time 1.529576 seconds, bootstrap likelihood -10073.326237, best rearrangement setting 8
Bootstrap[422]: Time 1.346310 seconds, bootstrap likelihood -9851.017887, best rearrangement setting 9
Bootstrap[423]: Time 1.565963 seconds, bootstrap likelihood -9447.100631, best rearrangement setting 14
Bootstrap[424]: Time 1.546573 seconds, bootstrap likelihood -9653.260634, best rearrangement setting 8
Bootstrap[425]: Time 1.614272 seconds, bootstrap likelihood -9954.279024, best rearrangement setting 6
Bootstrap[426]: Time 1.686986 seconds, bootstrap likelihood -9695.880086, best rearrangement setting 7
Bootstrap[427]: Time 1.507037 seconds, bootstrap likelihood -10073.360946, best rearrangement setting 5
Bootstrap[428]: Time 1.542293 seconds, bootstrap likelihood -9402.242727, best rearrangement setting 9
Bootstrap[429]: Time 1.511416 seconds, bootstrap likelihood -9601.343252, best rearrangement setting 15
Bootstrap[430]: Time 1.669742 seconds, bootstrap likelihood -9662.747312, best rearrangement setting 14
Bootstrap[431]: Time 1.781146 seconds, bootstrap likelihood -10462.485880, best rearrangement setting 14
Bootstrap[432]: Time 1.568606 seconds, bootstrap likelihood -9610.915873, best rearrangement setting 8
Bootstrap[433]: Time 1.853680 seconds, bootstrap likelihood -9829.597685, best rearrangement setting 13
Bootstrap[434]: Time 1.522258 seconds, bootstrap likelihood -10346.069704, best rearrangement setting 11
Bootstrap[435]: Time 1.367111 seconds, bootstrap likelihood -9834.442400, best rearrangement setting 8
Bootstrap[436]: Time 1.380121 seconds, bootstrap likelihood -9107.548358, best rearrangement setting 11
Bootstrap[437]: Time 3.355384 seconds, bootstrap likelihood -9829.714218, best rearrangement setting 15
Bootstrap[438]: Time 1.472449 seconds, bootstrap likelihood -9949.796519, best rearrangement setting 15
Bootstrap[439]: Time 1.549611 seconds, bootstrap likelihood -10282.353838, best rearrangement setting 13
Bootstrap[440]: Time 1.716915 seconds, bootstrap likelihood -9752.719809, best rearrangement setting 15
Bootstrap[441]: Time 1.549413 seconds, bootstrap likelihood -9302.770415, best rearrangement setting 14
Bootstrap[442]: Time 1.346809 seconds, bootstrap likelihood -9500.020691, best rearrangement setting 6
Bootstrap[443]: Time 1.545048 seconds, bootstrap likelihood -9975.276222, best rearrangement setting 7
Bootstrap[444]: Time 1.619399 seconds, bootstrap likelihood -9946.938208, best rearrangement setting 13
Bootstrap[445]: Time 1.510627 seconds, bootstrap likelihood -9308.585249, best rearrangement setting 14
Bootstrap[446]: Time 1.627995 seconds, bootstrap likelihood -9932.693500, best rearrangement setting 13
Bootstrap[447]: Time 1.697560 seconds, bootstrap likelihood -10160.841436, best rearrangement setting 11
Bootstrap[448]: Time 1.568160 seconds, bootstrap likelihood -9399.487671, best rearrangement setting 8
Bootstrap[449]: Time 1.573673 seconds, bootstrap likelihood -9446.121733, best rearrangement setting 10
Bootstrap[450]: Time 1.585407 seconds, bootstrap likelihood -9601.735356, best rearrangement setting 9
Bootstrap[451]: Time 1.432861 seconds, bootstrap likelihood -9705.317502, best rearrangement setting 9
Bootstrap[452]: Time 1.516508 seconds, bootstrap likelihood -9347.356784, best rearrangement setting 14
Bootstrap[453]: Time 1.471065 seconds, bootstrap likelihood -9812.567723, best rearrangement setting 10
Bootstrap[454]: Time 1.537758 seconds, bootstrap likelihood -9485.623167, best rearrangement setting 12
Bootstrap[455]: Time 3.640226 seconds, bootstrap likelihood -10437.795633, best rearrangement setting 11
Bootstrap[456]: Time 1.488995 seconds, bootstrap likelihood -10114.205853, best rearrangement setting 7
Bootstrap[457]: Time 1.500183 seconds, bootstrap likelihood -9575.827406, best rearrangement setting 7
Bootstrap[458]: Time 1.742922 seconds, bootstrap likelihood -10263.111896, best rearrangement setting 15
Bootstrap[459]: Time 1.399716 seconds, bootstrap likelihood -9570.438304, best rearrangement setting 8
Bootstrap[460]: Time 1.635893 seconds, bootstrap likelihood -9319.217951, best rearrangement setting 6
Bootstrap[461]: Time 1.500155 seconds, bootstrap likelihood -9803.059520, best rearrangement setting 5
Bootstrap[462]: Time 1.564364 seconds, bootstrap likelihood -9054.460587, best rearrangement setting 8
Bootstrap[463]: Time 1.509881 seconds, bootstrap likelihood -9788.037117, best rearrangement setting 10
Bootstrap[464]: Time 1.552235 seconds, bootstrap likelihood -9837.645926, best rearrangement setting 9
Bootstrap[465]: Time 1.502041 seconds, bootstrap likelihood -9771.701464, best rearrangement setting 8
Bootstrap[466]: Time 1.468342 seconds, bootstrap likelihood -10163.995117, best rearrangement setting 11
Bootstrap[467]: Time 1.643534 seconds, bootstrap likelihood -9777.215370, best rearrangement setting 13
Bootstrap[468]: Time 1.616555 seconds, bootstrap likelihood -10066.822210, best rearrangement setting 10
Bootstrap[469]: Time 1.760194 seconds, bootstrap likelihood -9392.889717, best rearrangement setting 15
Bootstrap[470]: Time 1.579391 seconds, bootstrap likelihood -9975.370321, best rearrangement setting 10
Bootstrap[471]: Time 1.431007 seconds, bootstrap likelihood -9463.736346, best rearrangement setting 7
Bootstrap[472]: Time 1.641434 seconds, bootstrap likelihood -10292.966527, best rearrangement setting 14
Bootstrap[473]: Time 3.485920 seconds, bootstrap likelihood -9550.942054, best rearrangement setting 11
Bootstrap[474]: Time 1.557382 seconds, bootstrap likelihood -9451.840195, best rearrangement setting 10
Bootstrap[475]: Time 1.576180 seconds, bootstrap likelihood -10006.339590, best rearrangement setting 8
Bootstrap[476]: Time 1.691073 seconds, bootstrap likelihood -9484.682644, best rearrangement setting 15
Bootstrap[477]: Time 1.557538 seconds, bootstrap likelihood -9771.627513, best rearrangement setting 9
Bootstrap[478]: Time 1.399200 seconds, bootstrap likelihood -9251.820177, best rearrangement setting 9
Bootstrap[479]: Time 1.499056 seconds, bootstrap likelihood -9678.913856, best rearrangement setting 7
Bootstrap[480]: Time 1.531391 seconds, bootstrap likelihood -9858.960021, best rearrangement setting 9
Bootstrap[481]: Time 1.640978 seconds, bootstrap likelihood -10300.288080, best rearrangement setting 10
Bootstrap[482]: Time 1.235617 seconds, bootstrap likelihood -9542.300847, best rearrangement setting 6
Bootstrap[483]: Time 1.325594 seconds, bootstrap likelihood -9615.900752, best rearrangement setting 6
Bootstrap[484]: Time 1.488296 seconds, bootstrap likelihood -9802.563718, best rearrangement setting 8
Bootstrap[485]: Time 1.450095 seconds, bootstrap likelihood -9420.859256, best rearrangement setting 8
Bootstrap[486]: Time 1.746751 seconds, bootstrap likelihood -9456.959700, best rearrangement setting 10
Bootstrap[487]: Time 1.556346 seconds, bootstrap likelihood -9358.926822, best rearrangement setting 13
Bootstrap[488]: Time 1.647521 seconds, bootstrap likelihood -10026.417536, best rearrangement setting 6
Bootstrap[489]: Time 1.552117 seconds, bootstrap likelihood -10368.812772, best rearrangement setting 5
Bootstrap[490]: Time 1.577961 seconds, bootstrap likelihood -9697.571711, best rearrangement setting 13
Bootstrap[491]: Time 3.815585 seconds, bootstrap likelihood -10095.980163, best rearrangement setting 6
Bootstrap[492]: Time 1.544863 seconds, bootstrap likelihood -9226.037756, best rearrangement setting 14
Bootstrap[493]: Time 1.542966 seconds, bootstrap likelihood -9962.800729, best rearrangement setting 7
Bootstrap[494]: Time 1.487720 seconds, bootstrap likelihood -10454.509921, best rearrangement setting 15
Bootstrap[495]: Time 1.639310 seconds, bootstrap likelihood -10501.019091, best rearrangement setting 13
Bootstrap[496]: Time 1.692095 seconds, bootstrap likelihood -10031.375917, best rearrangement setting 14
Bootstrap[497]: Time 1.593816 seconds, bootstrap likelihood -9959.119018, best rearrangement setting 12
Bootstrap[498]: Time 1.549800 seconds, bootstrap likelihood -9654.147976, best rearrangement setting 6
Bootstrap[499]: Time 1.739854 seconds, bootstrap likelihood -10147.219977, best rearrangement setting 9
Bootstrap[500]: Time 1.666460 seconds, bootstrap likelihood -10123.265094, best rearrangement setting 15
Bootstrap[501]: Time 1.480815 seconds, bootstrap likelihood -9857.283896, best rearrangement setting 13
Bootstrap[502]: Time 1.475464 seconds, bootstrap likelihood -9888.845268, best rearrangement setting 5
Bootstrap[503]: Time 1.258009 seconds, bootstrap likelihood -9658.401817, best rearrangement setting 11
Bootstrap[504]: Time 1.502113 seconds, bootstrap likelihood -9440.754473, best rearrangement setting 10
Bootstrap[505]: Time 1.310104 seconds, bootstrap likelihood -9607.405563, best rearrangement setting 6
Bootstrap[506]: Time 1.395803 seconds, bootstrap likelihood -9834.772108, best rearrangement setting 5
Bootstrap[507]: Time 1.378092 seconds, bootstrap likelihood -9460.444072, best rearrangement setting 9
Bootstrap[508]: Time 1.284950 seconds, bootstrap likelihood -9556.327270, best rearrangement setting 15
Bootstrap[509]: Time 4.403116 seconds, bootstrap likelihood -9822.643454, best rearrangement setting 14
Bootstrap[510]: Time 1.528404 seconds, bootstrap likelihood -10051.026775, best rearrangement setting 5
Bootstrap[511]: Time 1.458117 seconds, bootstrap likelihood -9028.008301, best rearrangement setting 11
Bootstrap[512]: Time 1.673560 seconds, bootstrap likelihood -10182.359290, best rearrangement setting 14
Bootstrap[513]: Time 1.512211 seconds, bootstrap likelihood -9490.444894, best rearrangement setting 12
Bootstrap[514]: Time 1.254480 seconds, bootstrap likelihood -9677.756238, best rearrangement setting 9
Bootstrap[515]: Time 1.472287 seconds, bootstrap likelihood -9968.773108, best rearrangement setting 6
Bootstrap[516]: Time 1.458243 seconds, bootstrap likelihood -9129.108981, best rearrangement setting 6
Bootstrap[517]: Time 1.393104 seconds, bootstrap likelihood -9894.339087, best rearrangement setting 6
Bootstrap[518]: Time 1.598007 seconds, bootstrap likelihood -9456.726482, best rearrangement setting 9
Bootstrap[519]: Time 1.629825 seconds, bootstrap likelihood -10118.271185, best rearrangement setting 13
Bootstrap[520]: Time 1.478763 seconds, bootstrap likelihood -9400.012951, best rearrangement setting 9
Bootstrap[521]: Time 1.546765 seconds, bootstrap likelihood -10239.396224, best rearrangement setting 10
Bootstrap[522]: Time 1.406624 seconds, bootstrap likelihood -9570.705862, best rearrangement setting 7
Bootstrap[523]: Time 1.410611 seconds, bootstrap likelihood -9723.149508, best rearrangement setting 6
Bootstrap[524]: Time 1.367435 seconds, bootstrap likelihood -9914.882413, best rearrangement setting 11
Bootstrap[525]: Time 1.716184 seconds, bootstrap likelihood -9833.309665, best rearrangement setting 8
Bootstrap[526]: Time 1.521812 seconds, bootstrap likelihood -9911.725956, best rearrangement setting 14
Bootstrap[527]: Time 4.539277 seconds, bootstrap likelihood -10166.929582, best rearrangement setting 12
Bootstrap[528]: Time 1.821791 seconds, bootstrap likelihood -10141.636646, best rearrangement setting 11
Bootstrap[529]: Time 1.572241 seconds, bootstrap likelihood -9865.979458, best rearrangement setting 7
Bootstrap[530]: Time 1.430467 seconds, bootstrap likelihood -9858.969469, best rearrangement setting 7
Bootstrap[531]: Time 1.590667 seconds, bootstrap likelihood -9919.951195, best rearrangement setting 12
Bootstrap[532]: Time 1.985902 seconds, bootstrap likelihood -10227.234132, best rearrangement setting 10
Bootstrap[533]: Time 1.773494 seconds, bootstrap likelihood -10101.609612, best rearrangement setting 12
Bootstrap[534]: Time 1.371971 seconds, bootstrap likelihood -9748.380244, best rearrangement setting 15
Bootstrap[535]: Time 1.388908 seconds, bootstrap likelihood -9326.950931, best rearrangement setting 6
Bootstrap[536]: Time 1.346231 seconds, bootstrap likelihood -9441.579533, best rearrangement setting 8
Bootstrap[537]: Time 1.594368 seconds, bootstrap likelihood -9986.449034, best rearrangement setting 8
Bootstrap[538]: Time 1.360362 seconds, bootstrap likelihood -9797.991436, best rearrangement setting 12
Bootstrap[539]: Time 1.664541 seconds, bootstrap likelihood -9956.010130, best rearrangement setting 9
Bootstrap[540]: Time 1.362524 seconds, bootstrap likelihood -9830.920751, best rearrangement setting 7
Bootstrap[541]: Time 1.549029 seconds, bootstrap likelihood -9744.230878, best rearrangement setting 7
Bootstrap[542]: Time 1.607740 seconds, bootstrap likelihood -9709.200650, best rearrangement setting 9
Bootstrap[543]: Time 1.525666 seconds, bootstrap likelihood -10110.102465, best rearrangement setting 8
Bootstrap[544]: Time 1.621921 seconds, bootstrap likelihood -9808.186479, best rearrangement setting 14
Bootstrap[545]: Time 1.546180 seconds, bootstrap likelihood -10241.477704, best rearrangement setting 10
Bootstrap[546]: Time 1.526711 seconds, bootstrap likelihood -9887.622112, best rearrangement setting 13
Bootstrap[547]: Time 1.474696 seconds, bootstrap likelihood -9592.148402, best rearrangement setting 8
Bootstrap[548]: Time 1.414512 seconds, bootstrap likelihood -9565.222391, best rearrangement setting 9
Bootstrap[549]: Time 1.589154 seconds, bootstrap likelihood -9644.081686, best rearrangement setting 12
Bootstrap[550]: Time 1.429311 seconds, bootstrap likelihood -9456.568851, best rearrangement setting 5
Bootstrap[551]: Time 1.573035 seconds, bootstrap likelihood -9615.178274, best rearrangement setting 10
Bootstrap[552]: Time 1.702150 seconds, bootstrap likelihood -10066.143737, best rearrangement setting 15
Bootstrap[553]: Time 1.515050 seconds, bootstrap likelihood -9482.577759, best rearrangement setting 13
Bootstrap[554]: Time 1.414655 seconds, bootstrap likelihood -9677.077471, best rearrangement setting 9
Bootstrap[555]: Time 1.759562 seconds, bootstrap likelihood -9395.224415, best rearrangement setting 9
Bootstrap[556]: Time 1.538313 seconds, bootstrap likelihood -9488.950159, best rearrangement setting 8
Bootstrap[557]: Time 1.623719 seconds, bootstrap likelihood -9856.453220, best rearrangement setting 12
Bootstrap[558]: Time 1.397881 seconds, bootstrap likelihood -9612.135799, best rearrangement setting 10
Bootstrap[559]: Time 1.652095 seconds, bootstrap likelihood -10066.048891, best rearrangement setting 13
Bootstrap[560]: Time 1.393132 seconds, bootstrap likelihood -9205.073693, best rearrangement setting 10
Bootstrap[561]: Time 1.556897 seconds, bootstrap likelihood -10267.296907, best rearrangement setting 7
Bootstrap[562]: Time 1.691337 seconds, bootstrap likelihood -9616.714546, best rearrangement setting 10
Bootstrap[563]: Time 3.533702 seconds, bootstrap likelihood -10329.748351, best rearrangement setting 12
Bootstrap[564]: Time 1.631695 seconds, bootstrap likelihood -9999.907077, best rearrangement setting 13
Bootstrap[565]: Time 1.681257 seconds, bootstrap likelihood -10163.439686, best rearrangement setting 12
Bootstrap[566]: Time 1.489771 seconds, bootstrap likelihood -9628.728174, best rearrangement setting 12
Bootstrap[567]: Time 1.824997 seconds, bootstrap likelihood -9234.176594, best rearrangement setting 9
Bootstrap[568]: Time 1.628015 seconds, bootstrap likelihood -9733.697425, best rearrangement setting 10
Bootstrap[569]: Time 1.546520 seconds, bootstrap likelihood -9862.310694, best rearrangement setting 7
Bootstrap[570]: Time 1.339426 seconds, bootstrap likelihood -9355.848860, best rearrangement setting 5
Bootstrap[571]: Time 1.722703 seconds, bootstrap likelihood -9616.783313, best rearrangement setting 13
Bootstrap[572]: Time 1.577478 seconds, bootstrap likelihood -10278.695565, best rearrangement setting 12
Bootstrap[573]: Time 1.390364 seconds, bootstrap likelihood -9600.664778, best rearrangement setting 12
Bootstrap[574]: Time 1.532887 seconds, bootstrap likelihood -9545.467992, best rearrangement setting 5
Bootstrap[575]: Time 1.734295 seconds, bootstrap likelihood -10245.363533, best rearrangement setting 14
Bootstrap[576]: Time 1.579730 seconds, bootstrap likelihood -9543.485826, best rearrangement setting 11
Bootstrap[577]: Time 1.600489 seconds, bootstrap likelihood -9892.877171, best rearrangement setting 6
Bootstrap[578]: Time 1.534474 seconds, bootstrap likelihood -9797.405966, best rearrangement setting 7
Bootstrap[579]: Time 1.394862 seconds, bootstrap likelihood -9889.330489, best rearrangement setting 15
Bootstrap[580]: Time 1.596119 seconds, bootstrap likelihood -9948.050619, best rearrangement setting 10
Bootstrap[581]: Time 3.160152 seconds, bootstrap likelihood -10043.861026, best rearrangement setting 10
Bootstrap[582]: Time 1.563020 seconds, bootstrap likelihood -10093.908034, best rearrangement setting 11
Bootstrap[583]: Time 1.440970 seconds, bootstrap likelihood -9467.625714, best rearrangement setting 11
Bootstrap[584]: Time 1.402459 seconds, bootstrap likelihood -10092.243055, best rearrangement setting 14
Bootstrap[585]: Time 1.556539 seconds, bootstrap likelihood -10454.438204, best rearrangement setting 14
Bootstrap[586]: Time 1.470406 seconds, bootstrap likelihood -9753.294324, best rearrangement setting 10
Bootstrap[587]: Time 1.567802 seconds, bootstrap likelihood -9610.218694, best rearrangement setting 14
Bootstrap[588]: Time 1.651639 seconds, bootstrap likelihood -10293.785235, best rearrangement setting 11
Bootstrap[589]: Time 1.521859 seconds, bootstrap likelihood -10199.747286, best rearrangement setting 5
Bootstrap[590]: Time 1.596652 seconds, bootstrap likelihood -9694.670715, best rearrangement setting 9
Bootstrap[591]: Time 1.500437 seconds, bootstrap likelihood -9773.273372, best rearrangement setting 6
Bootstrap[592]: Time 1.401806 seconds, bootstrap likelihood -9769.925677, best rearrangement setting 7
Bootstrap[593]: Time 1.579339 seconds, bootstrap likelihood -10190.219435, best rearrangement setting 5
Bootstrap[594]: Time 1.574653 seconds, bootstrap likelihood -10022.450798, best rearrangement setting 10
Bootstrap[595]: Time 1.540988 seconds, bootstrap likelihood -9995.867912, best rearrangement setting 5
Bootstrap[596]: Time 1.727873 seconds, bootstrap likelihood -10040.180622, best rearrangement setting 12
Bootstrap[597]: Time 1.601650 seconds, bootstrap likelihood -9964.700640, best rearrangement setting 15
Bootstrap[598]: Time 1.533980 seconds, bootstrap likelihood -10059.465353, best rearrangement setting 10
Bootstrap[599]: Time 3.761085 seconds, bootstrap likelihood -9821.630781, best rearrangement setting 13


Stopped Rapid BS search after 600 replicates with MRE-based Bootstopping criterion
WRF Average of 100 random splits: 1.703514
Overall Time for 600 Rapid Bootstraps 998.921731 seconds
Average Time per Rapid Bootstrap 1.664870 seconds

Starting ML Search ...

Fast ML optimization finished

Fast ML search Time: 690.311551 seconds

Slow ML Search 0 Likelihood: -9821.239742
Slow ML Search 1 Likelihood: -9821.239741
Slow ML Search 2 Likelihood: -9821.239741
Slow ML Search 3 Likelihood: -9821.239742
Slow ML Search 4 Likelihood: -9821.239742
Slow ML Search 5 Likelihood: -9821.239741
Slow ML Search 6 Likelihood: -9821.239741
Slow ML Search 7 Likelihood: -9821.239741
Slow ML Search 8 Likelihood: -9821.239741
Slow ML Search 9 Likelihood: -9821.239741
Slow ML optimization finished

Slow ML search Time: 50.817734 seconds
Thorough ML search Time: 8.149679 seconds

Final ML Optimization Likelihood: -9821.239741

Model Information:

Model Parameters of Partition 0, Name: No Name Provided, Type of Data: DNA
alpha: 0.423237
Tree-Length: 6.736015
rate A <-> C: 0.417396
rate A <-> G: 1.029964
rate A <-> T: 0.726730
rate C <-> G: 0.381269
rate C <-> T: 2.281964
rate G <-> T: 1.000000

freq pi(A): 0.256036
freq pi(C): 0.215030
freq pi(G): 0.323863
freq pi(T): 0.205071


ML search took 749.936289 secs or 0.208316 hours

Combined Bootstrap and ML search took 1748.861362 secs or 0.485795 hours

Drawing Bootstrap Support Values on best-scoring ML tree ...



Found 1 tree in File /N/dc2/projects/Lennon_Sequences/PhosTrait/RAxML_bestTree.LTDE.ML



Found 1 tree in File /N/dc2/projects/Lennon_Sequences/PhosTrait/RAxML_bestTree.LTDE.ML

Program execution info written to /N/dc2/projects/Lennon_Sequences/PhosTrait/RAxML_info.LTDE.ML
All 600 bootstrapped trees written to: /N/dc2/projects/Lennon_Sequences/PhosTrait/RAxML_bootstrap.LTDE.ML

Best-scoring ML tree written to: /N/dc2/projects/Lennon_Sequences/PhosTrait/RAxML_bestTree.LTDE.ML

Best-scoring ML tree with support values written to: /N/dc2/projects/Lennon_Sequences/PhosTrait/RAxML_bipartitions.LTDE.ML

Best-scoring ML tree with support values as branch labels written to: /N/dc2/projects/Lennon_Sequences/PhosTrait/RAxML_bipartitionsBranchLabels.LTDE.ML

Overall execution time for full ML analysis: 1748.905386 secs or 0.485807 hours or 0.020242 days

